feat(zsh): steal grml zsh options

diff --git a/tag-zsh/zshrc b/tag-zsh/zshrc
--- a/tag-zsh/zshrc
+++ b/tag-zsh/zshrc
@@ -17,6 +17,15 @@ if [[ $ZSH_PROFILE_RC -gt 0 ]] ; then
     zmodload zsh/zprof
 fi
 
+GRML_OSTYPE=$(uname -s)
+
+is_linux(){
+    [[ $GRML_OSTYPE == "Linux" ]]
+}
+
+is_darwin(){
+    [[ $GRML_OSTYPE == "Darwin" ]]
+}
 
 # Check for user and if not running as root set $SUDO to sudo.  Enables using
 # "$SUDO" in command definitions.
@@ -50,6 +59,128 @@ setopt inc_append_history_time
 # : 1472088207:4;sleep 4
 setopt extended_history
 
+# If a new command line being added to the history list duplicates an older one,
+# the older command is removed from the list (even if it is not the previous
+# event).
+setopt hist_ignore_all_dups
+
+# Remove command lines from the history list when the first character on the
+# line is a space, or when one of the expanded aliases contains a leading
+# space. Only normal aliases (not global or suffix aliases) have this behaviour.
+setopt hist_ignore_space
+
+# If a command is issued that can’t be executed as a normal command, and the
+# command is the name of a directory, perform the cd command to that
+# directory.
+setopt auto_cd
+
+# Display PID when suspending processes.
+setopt long_list_jobs
+
+# Report the status of backgrounds jobs immediately.
+setopt notify
+
+# Whenever a command completion or spelling correction is attempted, make sure
+# the entire command path is hashed first. This makes the first completion
+# slower but avoids false reports of spelling errors.
+setopt hash_list_all
+
+# If unset, the cursor is set to the end of the word if completion is
+# started. Otherwise it stays there and completion is done from both ends.
+setopt complete_in_word
+
+# Don't send SIGHUP to background processes when the shell exits.
+setopt nohup
+
+# Disable field splitting on unquoted parameter expansion.  This is different
+# from bash. For example
+#
+# var='foo bar'
+# args() { echo $#; }
+# args $var // produces 1, because zsh passes the string 'foo bar'.
+setopt no_sh_word_split
+
+# Avoid beeping on error in ZLE.
+setopt no_beep
+
+# Make cd push the old directory onto the directory stack.
+setopt auto_pushd
+
+# Don’t push multiple copies of the same directory onto the directory stack.
+setopt pushd_ignore_dups
+
+# Treat unset parameters as if they were empty when substituting. Otherwise they
+# are treated as an error.
+setopt unset
+
+# Declare global (-g), array (-a) parameters.
+typeset -ga ls_options
+typeset -ga grep_options
+if ls --color=auto / >/dev/null 2>&1; then
+    ls_options+=( --color=auto )
+elif ls -G / >/dev/null 2>&1; then
+    ls_options+=( -G )
+fi
+if grep --color=auto -q "a" <<< "a" >/dev/null 2>&1; then
+    grep_options+=( --color=auto )
+fi
+
+# Utility functions.
+
+# Checks if a command exists and returns either true or false. This avoids using
+# 'which' and 'whence', which will avoid problems with aliases for which on
+# certain weird systems.
+#
+# Usage: check_com [-c|-g] word
+#   -c  only checks for external commands
+#   -g  does the usual tests and also checks for global aliases
+check_com() {
+    emulate -L zsh
+    local -i comonly gatoo
+    comonly=0
+    gatoo=0
+
+    if [[ $1 == '-c' ]] ; then
+        comonly=1
+        shift 1
+    elif [[ $1 == '-g' ]] ; then
+        gatoo=1
+        shift 1
+    fi
+
+    if (( ${#argv} != 1 )) ; then
+        printf 'usage: check_com [-c|-g] <command>\n' >&2
+        return 1
+    fi
+
+    if (( comonly > 0 )) ; then
+        (( ${+commands[$1]}  )) && return 0
+        return 1
+    fi
+
+    if     (( ${+commands[$1]}    )) \
+        || (( ${+functions[$1]}   )) \
+        || (( ${+aliases[$1]}     )) \
+        || (( ${+reswords[(r)$1]} )) ; then
+        return 0
+    fi
+
+    if (( gatoo > 0 )) && (( ${+galiases[$1]} )) ; then
+        return 0
+    fi
+
+    return 1
+}
+
+# Color setup for ls.
+check_com -c dircolors && eval $(dircolors -b)
+# Color setup for ls on OS X / FreeBSD.
+is_darwin && export CLICOLOR=1
+
+# Automatically remove duplicates from these arrays.  Only keeps the first
+# occurence of each duplicated value.
+typeset -U path cdpath fpath manpath
+
 # Completion configuration.
 
 # The `-U` flag suppresses alias expansion and is recommended for functions
@@ -60,6 +191,7 @@ autoload -Uz compinit
 [[ -d "${ZDOTDIR:-$HOME}/.zcompdumps" ]] \
     || mkdir -m 0700 -p "${ZDOTDIR:-$HOME}/.zcompdumps"
 compinit -d "${ZDOTDIR:-$HOME}/.zcompdumps/${HOST%%.*}-$ZSH_VERSION"
+
 # https://github.com/zsh-users/zsh-completions/blob/master/zsh-completions-howto.org
 # has an in-depth explanation on how to write your own completions.
 #
